# Changes here will be overwritten by Copier
_commit: v1.3.3
_src_path: gh:lincc-frameworks/python-project-template
author_email: carlosg@uw.edu
author_name: University of Washington - SSEC
create_example_module: true
custom_install: true
include_notebooks: false
module_name: uwloc_data
mypy_type_checking: strict
preferred_linter: black
project_license: MIT
project_name: uwloc-db
use_gitlfs: none
use_isort: true
